server:
  port: 8080

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
  cloud:
    gateway:
      routes:
        - id: auth-service-route
          uri: lb://auth-service
          predicates:
            - Path=/auth/**, /register, /login, /.well-known/**
        - id: user-service-route
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
        - id: salon-service-route
          uri: lb://salon-service
          predicates:
            - Path=/api/salons/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
