server:
  port: 8080

spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
      
      routes:
        - id: auth-service-public-route
          uri: lb://auth-service
          predicates:
            - Path=/register, /login, /oauth2/**, /.well-known/**
        
        - id: user-service-route
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
        
        - id: salon-service-route
          uri: lb://salon-service
          predicates:
            - Path=/api/salons/**

        - id: offering-service-categories-route
          uri: lb://offering-service
          predicates:
            - Path=/api/categories/**

        - id: offering-service-offerings-route
          uri: lb://offering-service
          predicates:
            - Path=/api/service-offerings/**
