server:
  port: 8080

spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
  cloud:
    gateway:
      routes:
        # --- AUTHENTICATION ---
        - id: auth-service-public-route
          uri: lb://auth-service
          predicates:
            - Path=/register, /login, /oauth2/**, /.well-known/**
        
        # --- PROTECTED API ROUTES ---
        - id: user-service-route
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
        
        - id: salon-service-route
          uri: lb://salon-service
          predicates:
            - Path=/api/salons/**
            
        - id: offering-service-categories-route
          uri: lb://offering-service
          predicates:
            - Path=/api/categories/**

        - id: offering-service-offerings-route
          uri: lb://offering-service
          predicates:
            - Path=/api/service-offerings/**

        - id: booking-service-route # <-- Added missing route
          uri: lb://booking-service
          predicates:
            - Path=/api/bookings/**
            
        - id: payment-service-route
          uri: lb://payment-service
          predicates:
            - Path=/api/payments/**

      # --- GLOBAL CORS CONFIGURATION ---
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
