server:
  port: 9000

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/saloonbuddy_auth_db
    username: root
    password: root # Make sure this matches your docker-compose password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

auth:
  issuer-uri: http://localhost:9000
