server:
  port: 9004

spring:
  application:
    name: booking-service
  datasource:
    url: jdbc:mysql://localhost:3306/saloonbuddy_booking_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
