server:
  port: 9005

spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:mysql://localhost:3306/saloonbuddy_payment_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000

# Razorpay API Keys (read securely from environment variables)
razorpay:
  api:
    keyId: ${RAZORPAY_KEY_ID}
    keySecret: ${RAZORPAY_KEY_SECRET}
