server:
  port: 9002

spring:
  application:
    name: salon-service
  datasource:
    url: jdbc:mysql://localhost:3306/saloonbuddy_salon_db
    username: root
    password: root # Use the password from your docker-compose.yml
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
